'use strict';
const { v4: uuidv4 } = require('uuid');

module.exports = {
  async up(queryInterface, Sequelize) {
    // Get admin user
    const [admins] = await queryInterface.sequelize.query(
      `SELECT id FROM users WHERE role = 'admin' LIMIT 1`
    );
    const adminId = admins[0].id;

    const jobs = [
      {
        id: uuidv4(),
        title: 'Senior React Developer',
        company: 'TechCorp Inc.',
        description: 'We are looking for a Senior React Developer to join our growing team. You will be responsible for building and maintaining high-quality web applications using React.js and related technologies.',
        requirements: 'Strong proficiency in JavaScript and React.js\n5+ years of experience\nExperience with Redux, TypeScript\nKnowledge of RESTful APIs\nExperience with Git',
        responsibilities: 'Develop new user-facing features\nBuild reusable components\nOptimize applications for maximum speed\nCollaborate with backend developers',
        category: 'Technology',
        job_type: 'full-time',
        experience_level: 'senior',
        location: 'New York, USA',
        is_remote: false,
        salary_min: 120000,
        salary_max: 160000,
        salary_currency: 'USD',
        skills: '{React,JavaScript,Redux,TypeScript,REST API}',
        benefits: '{Health Insurance,401k,Remote Work,Stock Options}',
        status: 'active',
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        openings: 2,
        views_count: 145,
        applications_count: 23,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Full Stack Node.js Developer',
        company: 'StartupXYZ',
        description: 'Join our startup as a Full Stack Developer working on Node.js backend and React frontend. Exciting opportunity to work on cutting-edge technology.',
        requirements: '3+ years Node.js experience\nProficiency in React\nDatabase design skills (PostgreSQL/MongoDB)\nExperience with cloud services (AWS/GCP)',
        responsibilities: 'Design and implement backend services\nDevelop frontend features\nManage database design and optimization\nDeploy and maintain cloud infrastructure',
        category: 'Technology',
        job_type: 'full-time',
        experience_level: 'mid',
        location: 'San Francisco, USA',
        is_remote: true,
        salary_min: 100000,
        salary_max: 140000,
        salary_currency: 'USD',
        skills: '{Node.js,React,PostgreSQL,MongoDB,AWS}',
        benefits: '{Health Insurance,Flexible Hours,Remote Work,Equity}',
        status: 'active',
        deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 98,
        applications_count: 15,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'UI/UX Designer',
        company: 'DesignStudio',
        description: 'We need a talented UI/UX Designer to create amazing user experiences. You will work closely with product managers and engineers to ship great products.',
        requirements: '3+ years UI/UX experience\nProficiency in Figma and Adobe XD\nStrong portfolio\nKnowledge of design systems\nExperience with user research',
        responsibilities: 'Create wireframes and prototypes\nConduct user research\nDesign intuitive interfaces\nMaintain design system\nCollaborate with developers',
        category: 'Design',
        job_type: 'full-time',
        experience_level: 'mid',
        location: 'Austin, USA',
        is_remote: false,
        salary_min: 80000,
        salary_max: 110000,
        salary_currency: 'USD',
        skills: '{Figma,"Adobe XD","User Research","Design Systems",Prototyping}',
        benefits: '{Health Insurance,"Gym Membership","Creative Freedom","Learning Budget"}',
        status: 'active',
        deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 76,
        applications_count: 18,
        is_featured: false,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Digital Marketing Manager',
        company: 'GrowthHackers Ltd',
        description: 'Lead our digital marketing efforts across all channels. Drive growth through SEO, SEM, social media, and content marketing strategies.',
        requirements: '4+ years digital marketing experience\nExperience with Google Analytics, Ads\nSEO/SEM expertise\nContent marketing skills\nData-driven mindset',
        responsibilities: 'Develop marketing strategies\nManage ad campaigns\nOptimize SEO performance\nAnalyze and report metrics\nLead marketing team',
        category: 'Marketing',
        job_type: 'full-time',
        experience_level: 'senior',
        location: 'Chicago, USA',
        is_remote: true,
        salary_min: 90000,
        salary_max: 120000,
        salary_currency: 'USD',
        skills: '{SEO,SEM,"Google Analytics","Content Marketing","Social Media"}',
        benefits: '{Health Insurance,"Performance Bonus","Remote Work","Learning Budget"}',
        status: 'active',
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 54,
        applications_count: 12,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Financial Analyst',
        company: 'FinanceFirst Corp',
        description: 'Join our finance team as a Financial Analyst. Analyze financial data, create reports, and provide insights to support business decisions.',
        requirements: "Bachelor's degree in Finance or Accounting\n3+ years experience\nProficiency in Excel and financial modeling\nCFA certification preferred\nStrong analytical skills",
        responsibilities: 'Prepare financial reports\nConduct variance analysis\nDevelop financial models\nSupport budgeting process\nPresent findings to management',
        category: 'Finance',
        job_type: 'full-time',
        experience_level: 'mid',
        location: 'Boston, USA',
        is_remote: false,
        salary_min: 75000,
        salary_max: 100000,
        salary_currency: 'USD',
        skills: '{Excel,"Financial Modeling","Data Analysis",CFA,Bloomberg}',
        benefits: '{Health Insurance,401k,"Annual Bonus","Professional Development"}',
        status: 'active',
        deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
        openings: 2,
        views_count: 43,
        applications_count: 8,
        is_featured: false,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'DevOps Engineer',
        company: 'CloudNative Systems',
        description: 'We are seeking a skilled DevOps Engineer to help us build and maintain our cloud infrastructure. You will work on CI/CD pipelines, container orchestration, and cloud services.',
        requirements: '4+ years DevOps experience\nStrong knowledge of AWS/Azure/GCP\nExperience with Kubernetes and Docker\nCI/CD pipeline expertise\nInfrastructure as Code (Terraform)',
        responsibilities: 'Manage cloud infrastructure\nImplement CI/CD pipelines\nMonitor system performance\nAutomate deployment processes\nEnsure security best practices',
        category: 'Technology',
        job_type: 'full-time',
        experience_level: 'senior',
        location: 'Seattle, USA',
        is_remote: true,
        salary_min: 130000,
        salary_max: 170000,
        salary_currency: 'USD',
        skills: '{AWS,Kubernetes,Docker,Terraform,"CI/CD",Linux}',
        benefits: '{Health Insurance,401k,"Stock Options","Remote Work","Conference Budget"}',
        status: 'active',
        deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 67,
        applications_count: 9,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Healthcare Data Analyst',
        company: 'MediCare Solutions',
        description: 'Analyze healthcare data to improve patient outcomes and operational efficiency. Work with large datasets and create meaningful insights.',
        requirements: "Bachelor's degree in Healthcare Informatics or related field\n2+ years experience\nSQL proficiency\nExperience with Tableau or Power BI\nHealthcare domain knowledge",
        responsibilities: 'Analyze patient data\nCreate dashboards and reports\nIdentify trends and patterns\nCollaborate with clinical teams\nEnsure data quality',
        category: 'Healthcare',
        job_type: 'full-time',
        experience_level: 'junior',
        location: 'Houston, USA',
        is_remote: false,
        salary_min: 65000,
        salary_max: 85000,
        salary_currency: 'USD',
        skills: '{SQL,Tableau,"Power BI","Healthcare Analytics","Data Visualization"}',
        benefits: '{Health Insurance,"Dental Coverage","401k","Tuition Reimbursement"}',
        status: 'active',
        deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
        openings: 3,
        views_count: 38,
        applications_count: 14,
        is_featured: false,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Product Manager',
        company: 'ProductFirst Inc',
        description: 'Lead product strategy and execution for our SaaS platform. Work with cross-functional teams to deliver exceptional products that customers love.',
        requirements: '5+ years product management experience\nExperience with agile methodologies\nStrong analytical and communication skills\nTechnical background preferred\nExperience with product analytics tools',
        responsibilities: 'Define product vision and strategy\nManage product roadmap\nWork with engineering and design\nAnalyze user feedback and metrics\nLaunch new features',
        category: 'Operations',
        job_type: 'full-time',
        experience_level: 'senior',
        location: 'San Francisco, USA',
        is_remote: true,
        salary_min: 140000,
        salary_max: 180000,
        salary_currency: 'USD',
        skills: '{Agile,Scrum,"Product Strategy","User Research",JIRA,Analytics}',
        benefits: '{Health Insurance,"Unlimited PTO","Remote Work","Stock Options","Learning Budget"}',
        status: 'active',
        deadline: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 112,
        applications_count: 31,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Frontend Developer - Vue.js',
        company: 'WebSolutions Agency',
        description: 'Looking for a skilled Frontend Developer proficient in Vue.js to join our agency team. Work on diverse projects across multiple industries.',
        requirements: '2+ years Vue.js experience\nStrong HTML/CSS skills\nJavaScript proficiency\nExperience with REST APIs\nAttention to detail',
        responsibilities: 'Build responsive web applications\nImplement UI designs\nOptimize performance\nWrite clean, maintainable code\nWork with project managers',
        category: 'Technology',
        job_type: 'contract',
        experience_level: 'mid',
        location: 'Remote',
        is_remote: true,
        salary_min: 70000,
        salary_max: 95000,
        salary_currency: 'USD',
        skills: '{"Vue.js",JavaScript,HTML,CSS,"REST API",Git}',
        benefits: '{"Flexible Hours","Remote Work","Project Diversity","Quick Growth"}',
        status: 'active',
        deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        openings: 2,
        views_count: 89,
        applications_count: 27,
        is_featured: false,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        id: uuidv4(),
        title: 'Data Scientist',
        company: 'AI Innovations Lab',
        description: 'Join our AI research team as a Data Scientist. Work on machine learning models, natural language processing, and predictive analytics.',
        requirements: "Master's or PhD in Computer Science, Statistics, or related field\n3+ years experience\nPython and ML frameworks (TensorFlow, PyTorch)\nStrong statistics background\nExperience with big data technologies",
        responsibilities: 'Develop ML models\nAnalyze large datasets\nResearch new algorithms\nCollaborate with engineering team\nPresent findings to stakeholders',
        category: 'Technology',
        job_type: 'full-time',
        experience_level: 'senior',
        location: 'Boston, USA',
        is_remote: false,
        salary_min: 135000,
        salary_max: 175000,
        salary_currency: 'USD',
        skills: '{Python,"Machine Learning","Deep Learning",TensorFlow,PyTorch,SQL}',
        benefits: '{Health Insurance,"Research Budget","Conference Allowance","401k","Stock Options"}',
        status: 'active',
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        openings: 1,
        views_count: 156,
        applications_count: 42,
        is_featured: true,
        admin_id: adminId,
        created_at: new Date(),
        updated_at: new Date()
      }
    ];

    await queryInterface.bulkInsert('jobs', jobs);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('jobs', null, {});
  }
};